name: "Workflow that triggered from the test workflow"

on:
  workflow_dispatch:
    inputs:
      test_value:
        required: true
        type: string


jobs:
  test_run:
    runs-on: ubuntu-latest
    name:  Shared Workflow

    steps:
      - name: Echo input value
        run: echo ${{ inputs.test_value }}
